version: '3.9'

services:
  django_gunicorn:
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    env_file:
      - .env
    build:
      context: .
    ports:
    - "8008:8008"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  static_volume:
  media_volume: