# Generated by Django 4.2.1 on 2023-05-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='mehsul_adi',
        ),
        migrations.AddField(
            model_name='product',
            name='daxili_yaddas',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ekran',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='emeliyyat_sistemi',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='istehsalci',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='operativ_yaddas',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='qiymet',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='reng',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seriya',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sim_kartlarin_sayi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
