# Generated by Django 4.2.1 on 2023-05-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_product_name_product_mehsul_adi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sekil',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
